### ISSUE TITLE
beta0 output possible with snap.util.geocode?

### ISSUE THREAD

**Issue by peterfriedl** [johntruckenbrodt/pyroSAR#203]
I wonder if it is possible to generate beta0-images with snap.util.geocode. I only see gamma0 and sigam0 as possible output options. However, maybe there is a way to fork out beta0 from intermediate products generated during processing.
Thanks for helping!

**Comment by johntruckenbrodt** [comment]
Hi @peterfriedl. This option used to exist in earlier versions but I decided to remove it. In my opinion beta0 only really makes sense in radar geometry but is pretty useless in map geometry (because the backscatter of a pixel does no longer represent the area it covers). So I thought it would only be misleading if it could be selected as option.  
Do you see anything speaking against this?

**Comment by johntruckenbrodt** [comment]
Closing this since there has not been any update in a longer time
