### ISSUE TITLE
`archive.insert` wrongly registers scenes as duplicate because of non-unique `ID.outname_base`

### ISSUE THREAD

**Issue by maawoo** [johntruckenbrodt/pyroSAR#251]
[`archive.insert`](https://pyrosar.readthedocs.io/en/latest/api/drivers.html#pyroSAR.drivers.Archive.insert) relies on [`ID.outname_base`](https://pyrosar.readthedocs.io/en/latest/api/drivers.html#pyroSAR.drivers.ID.outname_base) to register scenes regularly or as duplicates. In the following example GRDs and SLCs are inserted into a new archive, however due to the non-unique `outname_base`, the SLC is not inserted regularly:

![image](https://github.com/johntruckenbrodt/pyroSAR/assets/56583917/2e48e92d-bf6e-46ea-8a16-022b871318b0)

**Comment by maawoo** [comment]
A solution could be to include `self.product` in `outname_base`, e.g.:  `S1B__SLC_IW___A_20211114T190431`. Not sure if there is another way around this problem.

**Comment by johntruckenbrodt** [comment]
You've caught a big one @maawoo. the method `outname_base` is an old one that is deep in the DNA of pyroSAR. Adding the product definitely needs to be done (too bad I didn't back when I wrote it). However, since this method is used in so many places this needs to be done with great care so that nothing gets broken along the way. I am not sure I will get to it this month.
