### ISSUE TITLE
Error handling if snap is not installed

### ISSUE THREAD

**Issue by ibaris** [johntruckenbrodt/pyroSAR#28]
Up to now pyroSAR raised an `ValueError` if snap was not installed. I changed this characteristic to an `UserWarning`. In my opinion it is more advantageous because if we check the snap installation in `snap\__init__.py` and snap is not installed we have not a chance to test the code due to the `ValueError` that is thrown at the import procedure. Now, if snap is not installed the following warning will appear:

```python
warnings.warn("One of the executables {0} should be installed. You can download it from http://step.esa.int/main/toolboxes/snap/ or you can specify a path with snap_config.set_path(path_to_snap)".format(name), UserWarning)
```

Now I am able to test the thrown `UserWarning` and we increase our coverage up to 27%. Moreover, I could not test the code with TRAVIS CI because the command `find_executable` does not work with TRAVIS. 

What do you think guys?

**Comment by johntruckenbrodt** [comment]
A `UserWarning` instead of an `ValueError` is fine. It is definitely good to test as much code as possible and I don't see a reason why a warning should not be enough here. Although we might need to implement some other error somewhere else in the `snap` module to give a meaningful error message when e.g. `gpt` is called but does not exist. Python will likely just throw a subprocess error saying `gpt` is not installed, which is harder to interpret than an explicit error saying SNAP is not installed. Please check this and catch the error in funtion `auxil.gpt` if necessary.
 Dou you know why `find_executable` doesn't work?

**Comment by ibaris** [comment]
Roger that! 

I do not know. I tried to find the snap installation also with `which snap`, `command -v snap` or with `locate  -r snap`. All attempts to locate snap on travis so far have failed.

**Comment by johntruckenbrodt** [comment]
ah okay. Usually SNAP is installed into a separate directory structure and not in the usual linux installation structure (with subdirectories `bin,` `lib`, `etc`, ...). Maybe you need to first add the path to the SNAP exectuables to the PATH environment. You can tell the SNAP installer where to install to in the unattended console mode. See [here](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/30539778/Install+SNAP+on+the+command+line). Try adding the subdirectory `bin` of the path you provide here to PATH and try it again.

**Comment by ibaris** [comment]
Thank you very much for the hint. At first I localize the snap installation directory with `ls -d /opt/snap/*/`. After that I add the `/bin` directory to $PATH via `export PATH=$PATH:/opt/snap/bin/`. Now the unit test fails because the class `ExamineExe` did not warn. Great! 

So, the `UserWarning` instead of `ValueError` will stay in the code, won't it?

**Comment by ibaris** [comment]
I tested the _dev_config module also. Not our coverage increased (+5.5%) to 30.026%.

**Comment by johntruckenbrodt** [comment]
nice one! The `UserWarning` is fine.
