### ISSUE TITLE
import pyroSAR.snap fails 

### ISSUE THREAD

**Issue by felixcremer** [johntruckenbrodt/pyroSAR#40]
If I try to import pyroSAR.snap it fails with the following Error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qe89hep/Programmieren/pyroSAR/pyroSAR/snap/__init__.py", line 4, in <module>
    snap_config = ExamineSnap()
  File "/home/qe89hep/Programmieren/pyroSAR/pyroSAR/snap/auxil.py", line 253, in __init__
    self.__get_etc()
  File "/home/qe89hep/Programmieren/pyroSAR/pyroSAR/snap/auxil.py", line 263, in __get_etc
    self.config_path = os.path.join(self.etc, [s for s in self.auxdata if "snap.auxdata.properties" in s][0])
IndexError: list index out of range
```

My Snap etc folder is at
/home/username/snap/etc
this is the location that is used automatically by the SNAP installer.

**Comment by felixcremer** [comment]
> My Snap etc folder is at
/home/username/snap/etc

Maybe it isn't. 
My snap is installed at /usr/bin/snap
and there is a .snap folder in my home with a etc folder. 
I think, this happens when we use the -dir option of the SNAP installer. 
This would need to be checked.

**Comment by ibaris** [comment]
In this case maybe it is more suitable to inform the user and give him an option to define the `etc` path manually. We could save the input in a config file to save the path automatically.

**Comment by ibaris** [comment]
After the pull request I would close this issue.

**Comment by ibaris** [comment]
I don't believe this!: **Issue #40 is NOT DEAD**.
But now I think know where the mistakes come from:

### 1. $PATH
In Linux operating systems, you can define the path variable in different ways. For example, a definition in `/etc/environment` would be as possible as in `~/.profile`. The name `profile` can be arbitrary, for example `~/.xprofile`. Here is an example why pyrosar does not find the snap application:

in ExamineExe we try to find the application with the command: https://github.com/johntruckenbrodt/pyroSAR/blob/15ce952ddd69d490ecd3944a47891f2caf69a6f7/pyroSAR/snap/auxil.py#L346  

In my case the variable `path` from row 346 contains:
```bash
['/usr/local/sbin',
 '/usr/local/bin',
 '/usr/sbin',
 '/usr/bin',
 '/sbin',
 '/bin',
 '/usr/games',
 '/usr/local/games',
 '/snap/bin',
 '/usr/lib/jvm/java-8-oracle/bin',
 '/usr/lib/jvm/java-8-oracle/db/bin',
 '/usr/lib/jvm/java-8-oracle/jre/bin']
```

But if I read the variables with the terminal, I get the following:
```bash
~$ echo $PATH
/home/xxx/snap/snap/snap/bin:/home/xxx/anaconda2/bin:/home/xxx/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
```
This means that the two paths do not match. Because only in the terminal `~$ echo $PATH` I get the path to the application snap: `/home/xxx/snap/snap/snap/bin`. Which brings us to the second point of error.

### 2. snap != snap
The path variable ` '/snap/bin',` that appears in the first path is not the path to the application snap! It is the [system /snap directory](https://docs.snapcraft.io/the-system-snap-directory/2817). However, we assume by line 345 
https://github.com/johntruckenbrodt/pyroSAR/blob/15ce952ddd69d490ecd3944a47891f2caf69a6f7/pyroSAR/snap/auxil.py#L345
that this is the path to the application. And that is not true! 

Maybe one could solve the problem by executing the commands `which` for Linux and `where` for Windows through the subprocess. If this is not executed successfully, then the application is not in the path. Then one could inform the user much better that he has to enter the application snap in the path. What do you think?

**Comment by ibaris** [comment]
With the command ´which´ it does not work either. In order to write the paper for the course "GRASS GIS" I have to add an option for the user to enter the path himself. Otherwise this does not work for me. Therefore I will have to make the changes in my fork. For this reason the proposed methods in the paper will probably only work with my PyroSAR fork. I will then trigger a pull request and you can decide if you want to add the option.

**Comment by johntruckenbrodt** [comment]
Hi Ismail,
yep I thought this issue would come up again eventually. Thanks for your elaboration on this.
Reagrding any user definition of the snap paths. I think it is better to add the directory directly to the .bashrc instead of adding an executable to the pyroSAR config. As long as a directory is contained in PATH, its executable should also be found by pyroSAR.
The list of defaults are only the names of the executable name options and not the paths themselves. Because snap can mean different things, e.g. the application manager in Ubuntu, I included several other tests to verify the ESA SNAP installation. For example, if an executable snap exists, also a file named "snap.auxdata.properties" must exist relative to it. If not, this particular option is discarded. See [here](https://github.com/johntruckenbrodt/pyroSAR/blob/15ce952ddd69d490ecd3944a47891f2caf69a6f7/pyroSAR/snap/auxil.py#L368).
`which` and `where` can be used via spatialist's function [which](https://github.com/johntruckenbrodt/spatialist/blob/ef1457506f96bdca5724ee509812e0dcbcbea054/spatialist/ancillary.py#L474).
Does that answer your questions? If not, can your elaborate a bit more on how exactly your system is set up and SNAP is installed?

**Comment by johntruckenbrodt** [comment]
Closed for now since no further import errors were discovered
