### ISSUE TITLE
Windows Testing: data format not supported

### ISSUE THREAD

**Issue by mustuner** [johntruckenbrodt/pyroSAR#53]
Hi,

I just tried to test it on Windows 10 (load the scene into pyroSAR for analysis of the metadata)

from pyroSAR import identify
name = 'S1A_IW_GRDH_1SDV_20150222T170750_20150222T170815_004739_005DD8_3768.zip'
scene = identify(name)
scene.summary()

The problem occured on the third line. Please see the error as following:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-be4ff1360999> in <module>()
      1 name = 'S1B_IW_GRDH_1SDV_20170119T041316_20170119T041341_003912_006BD4_26C0.zip'
----> 2 scene = identify(name)

c:\users\mustuner\anaconda3\lib\site-packages\pyrosar-0.3-py3.6.egg\pyroSAR\drivers.py in identify(scene)
     75         except (IOError, KeyError):
     76             pass
---> 77     raise RuntimeError('data format not supported')
     78 
     79 

RuntimeError: data format not supported

Thanks

**Comment by felixcremer** [comment]
Thank you for your report. 
We looked into it, and this issue is fixed on windows if we change the line 1997 in drivers.py from 
`membername = filename.replace(scene, `'').strip('/')

to 

`membername` = filename.replace(scene, '').strip('\\')

This change will most likely not working on Linux. Therefore, we need to find a way to make this operation OS independent.
