### ISSUE TITLE
Stacking function is not working

### ISSUE THREAD

**Issue by JohannesBalling** [johntruckenbrodt/pyroSAR#56]
## Problem description
Dear All,

so I was trying to use the _stack_ function on the pre-processed Sentinel-1 data (circa 20 images) to mosaic, stack and crop them. Unfortunately, that resulted in an error. It is worth mentioning that a temporal folder with all the .vrt files of the scenes was created during the call. The Gdal version I am using is 2.2.3.
See below the code I was using and the error message. 

Thank you very much in advance for your help.

## Code
```
import os

from pyroSAR.ancillary import finder
from pyroSAR.ancillary import groupbyTime
from pyroSAR.ancillary import seconds
from pyroSAR.spatial import stack

dir_in = '/media/DATA4/balli001/Data/01_Sumatra/01_Sentinel_1/02_pre_processed/01_test_small/'

dstfile = '/media/DATA4/balli001/Data/01_Sumatra/01_Sentinel_1/03_stack/01_stack_vv/test_vv_stack'

shp = '/media/DATA4/balli001/Data/01_Sumatra/05_additional_data/01_small_test_site/Small_test_site.shp'

sep = False

srcfiles = finder(dir_in, ['S1*_VV_*_dB.tif'])
    
# check whether dstfile is already a file
if os.path.isfile(dstfile):
	raise IOError('dstfile already exists')

groups = groupbyTime(srcfiles, seconds, 30)


# final function call
stack(srcfiles=groups, dstfile=dstfile, resampling='bilinear', targetres=[20, 20], srcnodata=0, dstnodata=-99, shapefile=shp, sortfun=seconds, separate=sep, overwrite=True)
```

## Error message
```
Traceback (most recent call last):
  File "02_stacking.py", line 36, in <module>
    stack(srcfiles=groups, dstfile=dstfile, resampling='bilinear', targetres=[20, 20], srcnodata=0, dstnodata=-99, shapefile=shp, sortfun=seconds, separate=sep, overwrite=True, cores=4)
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/spatial/raster.py", line 739, in stack
    gdalwarp(vrt, dstfile, options_warp)
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/spatial/auxil.py", line 126, in gdalwarp
    out = gdal.Warp(dst, src, options=gdal.WarpOptions(**options))
  File "/usr/lib/python2.7/dist-packages/osgeo/gdal.py", line 580, in Warp
    return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
  File "/usr/lib/python2.7/dist-packages/osgeo/gdal.py", line 3112, in wrapper_GDALWarpDestName
    return _gdal.wrapper_GDALWarpDestName(*args)
RuntimeError: Attempt to create 0x0 dataset is illegal,sizes must be larger than zero.
```
Greetings,

Johannes

**Comment by johntruckenbrodt** [comment]
Hi Johannes,
Thanks for your detailed error report. This is likely related to your defined target resolution. It needs to be in units of the source file CRS. Thus, if the unit is degrees, then you are trying to create a product with 20°x20° pixel size. You can either define the resolution in degrees or reprocess your data in a different CRS. For more details you can also look up the documentation of functions [stack](http://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.spatial.raster.stack) and [snap.geocode](http://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.snap.util.geocode).  
You can easily query the resolution of one of the images like this:
```Python
from pyroSAR.spatial import Raster
with Raster(srcfiles[0]) as ras:
    xres, yres = ras.res
```
We already encountered this case a few days ago and I will soon integrate a more meaningful error message. Admittedly, it's a bit confusing since `snap.geocode` explicitely asks for a target resolution in meters, but `stack` sure doesn't.
Does this solve your problem?

**Comment by JohannesBalling** [comment]
Hey John,

thank you very much for your fast reply. I just tried the target resolution in decimal degrees and that works just fine. Now its quite obvious what the mistake was. Thank you so much for your help though!

Greetings,
Johannes

**Comment by johntruckenbrodt** [comment]
Nice one! You're welcome.
Cheers
