### ISSUE TITLE
SNAP: problems to process using Assmebly

### ISSUE THREAD

**Issue by marielaraj** [johntruckenbrodt/pyroSAR#96]
Hello,
I am trying to process Sentinel 1 images using snap.geocode with Assemby and I am having a problem. I am not using thermal noise removal in this case and I am using an external DEM.

The log just says: java.lang.NullPointerException

 I attach the last lines:

Terrain-Flattening
  removing parameter Terrain-Flattening:reGridMethod and executing modified workflow
Terrain-Flattening
Executing processing graph
....11%...21%....32%java.lang.NullPointerException
java.lang.NullPointerException
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH does not contain the current folder '.'. Its value is '/home/software/GDAL-2.4.2/lib::/home/software/GAMMA_SOFTWARE-20181130/lib:/usr/local/lib'.
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
INFO: org.esa.snap.engine_utilities.download.DownloadableContentImpl: http retrieving http://step.esa.int/auxdata/dem/egm96/ww15mgh_b.zip
SEVERE: org.esa.snap.engine_utilities.download.DownloadableContentImpl: Failed to download remote file.
java.net.ConnectException: Connection refused (Connection refused)
(..)
failed: tmp4.dim

Thank you,Mariela.

**Comment by johntruckenbrodt** [comment]
SNAP is trying to download a file, but fails due to lack of internet access.
The file it is trying to download is required for the conversion of geoid heights (EGM96) to ellipsoid heights (WGS84). You can prevent this internal conversion by  setting `externalDEMApplyEGM=False` in the call of the [snap.geocode](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.snap.util.geocode) function.
Note however that this step is necessary for SAR processing. The documentation section on [DEM Preparation](https://pyrosar.readthedocs.io/en/latest/general/DEM.html) gives instructions on how to do this prior to processing.

**Comment by johntruckenbrodt** [comment]
This problem was solved in issue #98.
